TASK:
  TYPE: "Segmentation" # options are [Detection, Segmentation, Multitask]
MODEL:
  NUM_SEG_CLASSES: 94
  BACKBONE:
    NAME: "vovnet39"
    OUT_CHANNELS: (512, 768, 1024, 512)
    FEATURE_MAPS: (128, 64, 32, 16)
    FEATURE_INDICES: (1, 2, 3, 4)
    EXTRA: True
  HEAD:
    SEG_NAME: "DeepLabV3"
    LOSS_WEIGHTS: { "seg": 10 }
    ASPP_INDEX: 2
    DECODER_INDEX: 2
    OUTPUT_STRIDE: 16
INPUT:
  IMAGE_SIZE: 1024
DATASETS:
  TRAIN: ("vps_ah_dhl-train","vps_passenger_cars_batch1_complete-train","vps_passenger_cars_batch2_complete-train")
  TEST: ("vps_ah_dhl-val","vps_passenger_cars_batch1_complete-val","vps_passenger_cars_batch2_complete-val")
  PATH: "/home/lensor/Downloads/coco2017"
DATA_LOADER:
  LOCAL_MASKS: True
  NUM_WORKERS: 8
  INCLUDE_BACKGROUND: False
SOLVER:
  NAME: "SGD_optimizer"
  MAX_ITER: 400000
  LR_STEPS: [280000, 360000]
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 1e-4
  GAMMA: 0.1
  BATCH_SIZE: 2
  LR: 1e-3
TEST:
  BATCH_SIZE: 6
OUTPUT_DIR: "/home/lensor/Downloads/hardnet68_nanodet512_coco2017_seg"
