TASK:
  ENABLED: ["detection"] # options are [Detection, Segmentation, Multitask]
MODEL:
  HEADS:
    DETECTION:
      NUM_CLASSES: 36
      NAME: "NanoDet"
  BACKBONE:
    NAME: "vovnet39"
    OUT_CHANNELS: (512, 768, 1024)
    FEATURE_MAPS: (64, 32, 16)
    FEATURE_INDICES: (1, 2, 3)
    EXTRA: True
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ["ocr_v5-train"]
  TEST: ["ocr_v5-test"]
  #  This is the local path (not required for ClearML)
  PATH: "/home/lensor/Documents/Datasets/ocr_v5_new"
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 8
  INCLUDE_BACKGROUND: False
SOLVER:
  OPTIMIZER: "SGD_optimizer"
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 1e-4
  GAMMA: 0.1
  BASE_LR: 1e-3
OUTPUT_DIR: "/home/lensor/Downloads/multitask_training/vovnet39_nanodet512_dd"
