TASK:
  ENABLED: ["detection"] # options are [Detection, Segmentation, Multitask]
MODEL:
  HEADS:
    DETECTION:
      NUM_CLASSES: 11
      NAME: "NanoDet"
  BACKBONE:
    NAME: "vovnet39"
    OUT_CHANNELS: (512, 768, 1024)
    FEATURE_MAPS: (96, 48, 24)
    FEATURE_INDICES: (1, 2, 3)
    EXTRA: True
INPUT:
  IMAGE_SIZE: 768
DATASETS:
  TRAIN: ["damage_detection_old-train"]
  TEST: ["damage_detection_old-val"]
  #  This is the local path (not required for ClearML)
  PATH: "/media/lensor/2TBdrive/datasets/damage_detection_old/ddd_torno"
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 8
  INCLUDE_BACKGROUND: False
SOLVER:
  OPTIMIZER: "SGD_optimizer"
  MAX_ITER: 640000
  LR_STEPS: [450000, 570000]
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 1e-4
  GAMMA: 0.1
  BASE_LR: 1e-3
OUTPUT_DIR: "/home/lensor/Downloads/multitask_training/vovnet_nanodet768_dd/test_output"
