TASK:
  ENABLED: ["segmentation"] # options are [Detection, Segmentation, Multitask]
MODEL:
  HEADS:
    DETECTION:
      NUM_CLASSES: 80
    SEGMENTATION:
      NAME: "ESPNetV2"
      LOSS_WEIGHTS: { "seg": 10 }
  BACKBONE:
    NAME: "HarDNet68"
    OUT_CHANNELS: (320, 640, 1024, 512, 512)
    FEATURE_MAPS: (64, 32, 16, 8, 4)
    FEATURE_INDICES: (1, 2, 3, 4, 5)
    EXTRA: True
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ["coco_2017_stuff-train"]
  TEST: ["coco_2017_stuff-val"]
  PATH: "/home/lensor/Downloads/coco2017"
DATALOADER:
  BATCH_SIZE: 2
  LOCAL_MASKS: False
  NUM_WORKERS: 8
  INCLUDE_BACKGROUND: False
SOLVER:
  OPTIMIZER: "SGD_optimizer"
  MAX_ITER: 80000
  LR_STEPS: [560000, 720000]
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 1e-4
  GAMMA: 0.1
  BASE_LR: 1e-3
TEST:
  BATCH_SIZE: 6
OUTPUT_DIR: "/home/lensor/Downloads/hardnet68_nanodet512_coco2017_seg"
